# Reference: https://github.com/repository-settings/app

_extends: .github

repository:
  name: client-library-capacitor
  description: integrate your Capacitor app with mytiki.com
  homepage: https://docs.mytiki.com/reference/client-library-overview
  topics: capacitor, library
  private: false
  has_projects: true
  has_discussions: false

teams:
  - name: sysadmin
    permission: admin
  - name: engineering
    permission: push
  - name: product
    permission: triage
  - name: frontend
    permission: push

environments:
  - name: production

branches:
  - name: main
    protection:
      required_status_checks:
        strict: true
        contexts:
          - Analyze Project
          - Analyze (javascript-typescript)

milestones:
  - title: 0.2.1
    description: DRAFT
    state: open
